### ISSUE TITLE
pin bioimageio.spec

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/core-bioimage-io-python#135]
the test failures with the conda package (the latest release is sitll pending) makes me think we should pin bioimageio.spec here. otherwise installing any past version is virtually impossible...

I stumbled over the absence of bioimageio.spec pinning in https://github.com/bioimage-io/core-bioimage-io-python/issues/134#issuecomment-947924488_

and after some discussion with @k-dominik came to the conclusion that we should pin bioimageio.spec exactly while in 0.x.x (and afterwards down to minor)

**Comment by constantinpape** [comment]
Will be fixed by #143
