### ISSUE TITLE
Support model unloading

### ISSUE THREAD

**Issue by oeway** [bioimage-io/core-bioimage-io-python#150]
Would be nice to have a function to unload the model and free the GPU memory.

**Comment by FynnBe** [comment]
in tiktorch we achieve this by brute force with subprocesses: Spawn a subprocess for a model (in tiktorch we call this a session) and then just end it when not needed anymore. When evaluating options this seemed to be the most reliable option. (there are many issues that can lead to occupied memory.) Would this be somehow feasable for the triton server as well?

**Comment by oeway** [comment]
@FynnBe I think it's possible but not within the model itself, we will need to implement another server software to control model loading and unloading. This means user won't have direct access to triton which is less ideal.

**Comment by FynnBe** [comment]
alright, for this to work reliably for all frameworks we might take a few iterations, but let's just give it a go...

**Comment by FynnBe** [comment]
#155 added unload for pytorch
closing this issue in favor of #162 to discuss missing TF/Keras unloading
