### ISSUE TITLE
ImplicitOutputShape is not properly validated?!

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#158]
We specify that `shape = shape(input_tensor) * scale + 2 * offset` for the `ImplicitOutputShape`, see https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_latest.md.
However, it seems like this is not properly checked in `bioiamgeio test-model`:
`test-model` passes for https://github.com/bioimage-io/spec-bioimage-io/blob/main/example_specs/models/stardist_example_model/rdf.yaml#L39; however, the correct value would be 33 / 2.
@FynnBe we should make sure that the ImplicitOutputShape (and also InputShape etc.) are validated for the test input / outputs.
Is `test-model` the best place to do this or can we do it even earlier in validation?

**Comment by FynnBe** [comment]
after "offline" discussion:
in `bioimageio validate` we do not test if the specified files even exist. For simplicity we should keep it that way, which avoids any trouble running the validate command in pyodide, etc.
Therefore I will add the check for shape matching of test data and description to `bioimageio test-model` here in core.

**Comment by FynnBe** [comment]
in the docs we do not specify how we round the `shape(input_tensor) * scale` part? [`numpy.round_()`](https://numpy.org/doc/stable/reference/generated/numpy.round_.html) to dodge the specifics on our side?
