### ISSUE TITLE
Add information about which weights have been tested in command test-model

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/core-bioimage-io-python#171]
cc @constantinpape @esgomezm

**Comment by FynnBe** [comment]
and while we're at it map '-' weight formats to '_' ones (which are the only valid names atm). e.g. "keras-hdf5" -> "keras_hdf5". 
the -/_ difference is confusing as commands and arguments are all with dash and not with underscore, while the weight formats as input values are not interpreted in that way.

**Comment by constantinpape** [comment]
I have added the message in d6a8ff0.
