### ISSUE TITLE
remove enforce_min_shape

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/core-bioimage-io-python#198]
I don't know if the `enforce_min_shape` function is used anywhere, besides in ilastik (given that it's in a private module), but it only works for special, albeit common, cases where increments are the same in all directions. It also has other flaws, like not taking channels/time/datatype into account.

https://github.com/bioimage-io/core-bioimage-io-python/blob/55ed67201377224e6e8e3fe626f1f470fddd1503/bioimageio/core/prediction_pipeline/_prediction_pipeline.py#L149-L174

I'd actually suggest to remove it if it is not necessary anymore? In ilastik we'll do something else...

**Comment by constantinpape** [comment]
I am not using it anywhere, so fine for me to remove this.

**Comment by constantinpape** [comment]
@FynnBe any reason why we might still need `enforce_min_shape`? Otherwise I will remove it.
