### ISSUE TITLE
"Unknown" is serialized to attachments

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#204]
`unknown: {}` is serialized to `attachments` when using `build_spec` (which uses `export_resource_package` internally).
It should not be serialized, because this is something internally added by the spec library. See e.g. [this model](https://oc.embl.de/index.php/s/k087NMVaH5PBNxU).

**Comment by FynnBe** [comment]
can't reproduce this with the package command.:
```
python -m bioimageio.core package https://oc.embl.de/index.php/s/k087NMVaH5PBNxU/download
bioimageio.spec 0.4.2post3
implementing:
        collection RDF 0.2.2
        general RDF 0.2.2
        model RDF 0.4.2
bioimageio.core 0.4.9
download: 100%|█████████████████████████████████████████|37.6M/37.6M [00:57<00:00, 651kiB/s]
exported bioimageio package from https://oc.embl.de/index.php/s/k087NMVaH5PBNxU/download to download-package.zip
```
does not have any `unknown` field in download-package.zip/rdf.yaml...

**Comment by constantinpape** [comment]
The problem is that `attachment:unknown` **is** in the rdf of this model, see:
![image](https://user-images.githubusercontent.com/4263537/150634571-1565287f-74b7-47f7-bfc5-c0961210c08b.png)

And it ends up there because it's created via `build_spec`, which uses `export_resource_package` internally. So something in there serializes the `unknown` field to the rdf.yaml; which should not happen.

**Comment by constantinpape** [comment]
See also the test errors here: https://github.com/bioimage-io/core-bioimage-io-python/pull/207

**Comment by FynnBe** [comment]
I suppose it has been fixed in the meantime and the model was generated at an unfortunate moment in bioimageio.spec post release history^^
see comment [here](https://github.com/bioimage-io/core-bioimage-io-python/pull/207#issuecomment-1021031023)

**Comment by constantinpape** [comment]
Cool, thaks for checking.
