### ISSUE TITLE
[Question/Improvement]: Spec update script

### ISSUE THREAD

**Issue by tomburke-rse** [bioimage-io/core-bioimage-io-python#205]
Hi people,

are there any plans to add a version updater to this script?
E.g. if I validate a model spec 0.3.2 I see whats missing/wrong. Now I want to update it to latest, in the best case through a dialog system. I know that isn't exactly easy and might be more interesting the more stable we get, but is this something that is in the future scope?

**Comment by constantinpape** [comment]
This is already supported. @FynnBe would know best which function exactly to call (and which arguments to pass) in order to update models.

**Comment by tomburke-rse** [comment]
I didn't see it in the Readme and didn't look further inside, but if this already exists. Great!

**Comment by FynnBe** [comment]
@tomburke-rse , there is no dialog system (yet), but the validator can try to auto-convert and then yield the errors and warnings for the specified higher version. Atm we only support upgrading, no downgrading of the format version.

I am updating the documentation in https://github.com/bioimage-io/spec-bioimage-io/pull/376
Happy about any feedback. The update-format command has not been heavily used and could probably be improved... - again - any feedback is very welcome ;-)

**Comment by tomburke-rse** [comment]
I'll check it out and give feedback about the update-feature as soon as possible. I would also only support update to *latest, as I see no value to downgrade at all.

**Comment by FynnBe** [comment]
@tomburke-rse does this need more discussion or does everything work as expected?

**Comment by tomburke-rse** [comment]
Nope, I'm happy with it as it is. :)
