### ISSUE TITLE
No such command 'test-model'

### ISSUE THREAD

**Issue by oeway** [bioimage-io/core-bioimage-io-python#213]
Hi, any idea why the command doesn't work after installing it with `pip install -U bioimageio.core`?
```
~$ bioimageio test-model 10.5281/zenodo.5910855
Usage: bioimageio [OPTIONS] COMMAND [ARGS]...
Try 'bioimageio -h' for help.

Error: No such command 'test-model'.
```

**Comment by constantinpape** [comment]
Not sure, could you try deinstalling `bioimageio.core` completely and then install it just via `pip install bioimageio.core`?

**Comment by FynnBe** [comment]
maybe you have installed `bioimage.spec` after core, such that it runs the spec version of the bioimageio command...

**Comment by oeway** [comment]
I tried uninstall both and reinstall them but still not working. However I manage to run with a conda environment. 

I am a bit confused that when we have two packages sharing the same  entry point command bioimageio what will happen? Will both work?

**Comment by constantinpape** [comment]
ok, so maybe this is an issue with the pip installation. I guess we never really test the pip installation because everyone here is using conda.

> I am a bit confused that when we have two packages sharing the same entry point command bioimageio what will happen? Will both work?

No, the second one to be installed over-rides the first one; at least that's how it's working for us in conda.

**Comment by constantinpape** [comment]
I assume this is resolved, feel free to reopen if not @oeway.
