### ISSUE TITLE
Incorrect type annotations in processing?

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#221]
Feedback from @tomburke-rse: the [processing implementation](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/tests/prediction_pipeline/test_preprocessing.py) seems inconsistent with the spec definition, because some operations don't allow passing arrays for the arguments where it should be supported (according to type annotations)
This is the case for:
- [percentiles in scale_range](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction_pipeline/_processing.py#L167-L168)
- [mean and std in zero_mean_unit_variance](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction_pipeline/_processing.py#L229-L230)

I am pretty sure that this is just missing type annotations and that it's actually supported to pass arrays there.

**Comment by FynnBe** [comment]
not quite. The Percentile class is directly used there and it supports only floats:
https://github.com/bioimage-io/core-bioimage-io-python/blob/ce27bb2ff73288cf83b99af78b564e72c1610a90/bioimageio/core/statistical_measures.py#L21-L27

**Comment by constantinpape** [comment]
@tomburke-rse small correction to what we discussed earlier:
for `ScaleRange` we always just pass a scalar for `min/max_percentile`. `axes` then change how the percentiles are computed.
Take the example of an image with 3 channels (`axes = xyc`).
- If `axes` is not passed to `ScaleRange`, the percentiles are computed over all of the data, so we end up with a single `min/max` value that is used for normalization
- If `axes="yx"` is passed, the percentiles are computed independently for the three axes and we end up with 3 values for min/max respectively that are used to normalize the 3 individual channels.

In python pseudo code:
```python
input = np.array((128, 128, 3))  # the image with 3 channels
if axes is None:
  min, max = np.percentile(input, min_percentile), np.percentile(input, max_percentile)
  out = (input - min) / max
elif axes == "xyc":
   out = np.zeros_like(input)
   for c in range(input.shape[-1]):
         min, max = np.percentile(input[..., c], min_percentile), np.percentile(input[..., c], max_percentile)
         out[..., c] = (input - min) / max
```

For `ZeroMeanUnitVariance` what I told you is correct and there is indeed just a wrong type annotation in the code; @FynnBe will fix this.

**Comment by constantinpape** [comment]
Hey @FynnBe, could you fix the incorrect type annotations so that we can close this?

**Comment by FynnBe** [comment]
I'm a bit confused, but ZeroMeanUnitVariance is now annotaed to accept sequences for mean, std: https://github.com/bioimage-io/core-bioimage-io-python/blob/f520119bace6a41c41b6560cc9495f038a34d30f/bioimageio/core/prediction_pipeline/_processing.py#L241-L242

ScaleMeanVariance is not yet implemented, but asaik not in use and not part of this issue... 
https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/prediction_pipeline/_processing.py#L170-L172

Please reopen if I am overlooking something
