### ISSUE TITLE
Improve 404 errors

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/core-bioimage-io-python#243]
...
Also, the error message here is very confusing; it fails to load the input numpy data (because this is a text file that contains the 404 error message.) We should update the `requests` call that is used for downloading so that it actually catches these errors and doesn't just write the error to file ...

_Originally posted by @constantinpape in https://github.com/bioimage-io/collection-bioimage-io/pull/301#issuecomment-1064881082_

**Comment by constantinpape** [comment]
Fixed by https://github.com/bioimage-io/spec-bioimage-io/pull/425
