### ISSUE TITLE
Wrong specyfication of pytorch extra requirements are wrongly specified

### ISSUE THREAD

**Issue by Czaki** [bioimage-io/core-bioimage-io-python#286]
The name of `pytorch` package on pypi is `torch`. The `cudatoolkit` package does not exist on pypi.

https://github.com/bioimage-io/core-bioimage-io-python/blob/e335077dfaa282fb4982b85ef17cb46ddd939837/setup.py#L41

I could make PR with fixes if you want.

**Comment by oeway** [comment]
HI @Czaki Thanks for pointing this out. yes, please make a PR for this!

**Comment by Czaki** [comment]
Are you interested in modernization of your config by moving the static part of the configuration from `setup.py` to `setup.cfg`/`pyproject.toml`?

**Comment by constantinpape** [comment]
> Are you interested in modernization of your config by moving the static part of the configuration from `setup.py` to `setup.cfg`/`pyproject.toml`?

Let's discuss further in #287. @FynnBe can you please take a look there.
