### ISSUE TITLE
0.5.6 contains breaking changes

### ISSUE THREAD

**Issue by uschmidt83** [bioimage-io/core-bioimage-io-python#297]
Hi, I noticed that 0.5.6 breaks [our tests](https://github.com/stardist/stardist/actions/runs/3084587929/jobs/4986909452) in StarDist. I did some digging and think the reason is that `bioimageio.core.resource_tests.test_model` doesn't return a dict anymore, but instead a list (changed in [this commit](https://github.com/bioimage-io/core-bioimage-io-python/commit/4dccc013ee39b1e2f9d875f9a73ca4fe428b75cc)).

Any pointers on how I need to update [my code](https://github.com/stardist/stardist/blob/f73cdc44f718d36844b38c1f1662dbb66d157182/tests/test_bioimageio.py#L12-L24)?

**Comment by FynnBe** [comment]
for reference: this was first changed in a988b7c4070100d334fc1fb03bfde6cf4f695b9d

I made a PR that should fix it: https://github.com/stardist/stardist/pull/209

we changed to a list of tests to be more consistent with `test_resource` which may run multiple tests. We might expand `test_model` accordingly. Atm the returned list of `test_model` always has only one entry.

**Comment by uschmidt83** [comment]
> Atm the returned list of `test_model` always has only one entry.

Are you sure? Is [this](https://github.com/bioimage-io/core-bioimage-io-python/blob/b0ceac8fa5b412b1ea811c442697de2150fa1b90/bioimageio/core/resource_tests.py#L257-L259) not run when called via `test_model`?

**Comment by FynnBe** [comment]
> Are you sure? Is [this](https://github.com/bioimage-io/core-bioimage-io-python/blob/b0ceac8fa5b412b1ea811c442697de2150fa1b90/bioimageio/core/resource_tests.py#L257-L259) not run when called via test_model?

you are right! there are already more than one test for models!
