### ISSUE TITLE
Read information about required number of channels for a given model

### ISSUE THREAD

**Issue by Czaki** [bioimage-io/core-bioimage-io-python#298]
Is there any official API to determine how many channels are required by a given model stored in bioimage-io format?

Part of my job is implementing a universal GUI that allows evaluating a model on user data to check how it works with user data for PartSeg/napari. 

The possibility to adjust the parameters of visualization of each data channel separately is an essential functional requirement. Also, a user could have more channels in data than the model creator uses to train it. So it would be nice if the interface could adjust to the model rather than require the user to search for such information in the description or understand traceback.

In the future, it will be nice to allow model creators to annotate channels with semantic descriptions, which is expected input that could be rendered in the interface (label or tooltip). I do not find such a possibility in a current model.

**Comment by FynnBe** [comment]
bioimageio.spec defines the 'model RDF', where you find the `inputs` field: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/model_spec_0_4.md#inputs

thus, for a given model resource you could use `model = bioimageio.spec.load_raw_resource_description(model_rdf)` and then check `model.inputs`.

To extend the inputs/outputs metadata we have this issue: https://github.com/bioimage-io/spec-bioimage-io/issues/290

**Comment by Czaki** [comment]
So, in general, if `inputs.shape.min` on the axis that corresponds to channel in `inputs.axes` will always informal number of required channels?

(If explicit shape is provided then, it could be read from this)

**Comment by FynnBe** [comment]
yes, you probably want to double check that `inputs.shape.step` has a zero in the channel dim, otherwise the model would accept a range of input channels (which you probably don't want to support for now. I don't think any current model has this edge case).

**Comment by FynnBe** [comment]
please reopen if there are more questions!
