### ISSUE TITLE
Validator does not run the last version of the spec written by the library

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/core-bioimage-io-python#303]
I exported the model using the last version of the bioimageio.core library but when I click on validate in the Upload, it outputs the following error (my rdf.yaml has format 0.4.8):

<img width="1015" alt="Screenshot 2022-10-28 at 18 40 08" src="https://user-images.githubusercontent.com/43643518/198688880-581ee79c-d2de-48ae-9c3c-b5af6f8274c2.png">

@FynnBe @constantinpape

**Comment by FynnBe** [comment]
this is because the uploader uses the pinned version 0.4.6 of bioimageio.spec... 
I made a PR to update the uploader: https://github.com/bioimage-io/spec-bioimage-io/pull/481
