### ISSUE TITLE
Weight conversion error from GPU/CPU weights 

### ISSUE THREAD

**Issue by ivan-ea** [bioimage-io/core-bioimage-io-python#308]
I got the following error when trying to use the
`convert-torch-weights-to-torchscript` command on the CLI.  

````
\bioimageio\core\weight_converter\torch\utils.py:9 in load_model     
│                                                                                                  │
│    6 # and for each weight format                                                                │
│    7 def load_model(node):                                                                       │
│    8 │   model = PytorchModelAdapter.get_nn_instance(node)                                       │
│ >  9 │   state = torch.load(node.weights["pytorch_state_dict"].source)                           │
│   10 │   model.load_state_dict(state)                                                            │
│   11 │   model.eval()                                                                            │
│   12 │   return model

RuntimeError: Attempting to deserialize object on a CUDA device but
torch.cuda.is_available() is False. If you are running on a CPU-only machine,
please use torch.load with map_location=torch.device('cpu') to map your storages
to the CPU.
````

The problem appeared when using the models:
- 3d-unet-mouse-embryo-live [powerful-fish](https://bioimage.io/#/?tags=plantseg&type=model&id=10.5281%2Fzenodo.6384845)
- 2d-unet-arabidopsis-apical-stem-cells [laid-back-lobster](https://bioimage.io/#/?tags=plantseg&type=model&id=10.5281%2Fzenodo.6334881)

**Comment by constantinpape** [comment]
Yes, this is a problem for models that were saved with the weights on the GPU. In this case we can just load the model on the cpu by default, which will be done by #309. (It will take a few days till we get out a release with these changes, if you don't want to wait for this you can just go ahead and make this change locally.)

**Comment by ivan-ea** [comment]
Thank you @constantinpape I will try changing it locally for the time being.
