### ISSUE TITLE
Error if no preprocessing when adding deepimagej config

### ISSUE THREAD

**Issue by ivan-ea** [bioimage-io/core-bioimage-io-python#314]
I think there is an issue with the  `_get_deepimagej_config` function.

The `build_model` function generates the correct ouput when working with a model
with preprocessing (i.e.  [wild-whale](https://bioimage.io/#/?id=10.5281%2Fzenodo.6079314)), it produces the `sample.tifs` and `rdf.yaml` correctly. 
But, the plantseg models do not have preprocessing, and the error below appears.

````
Traceback (most recent call last):

  File "C:\Users\hestevez\.conda\envs\bio-conv-weights\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\hestevez\repos\bioimage_22\code\bioimage\modify_models.py", line 159, in <module>
    build_model(tags = list(set(model_dict['tags'] + NEW_TAGS)),

  File "C:\Users\hestevez\.conda\envs\bio-conv-weights\lib\site-packages\bioimageio\core\build_spec\build_model.py", line 842, in build_model
    ij_config, ij_attachments = _get_deepimagej_config(

  File "C:\Users\hestevez\.conda\envs\bio-conv-weights\lib\site-packages\bioimageio\core\build_spec\build_model.py", line 412, in _get_deepimagej_config
    return {"deepimagej": config}, [Path(a) for a in attachments]

TypeError: 'NoneType' object is not iterable
````

An easy way to reproduce the error is running the [model creation notebook](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/example/model_creation.ipynb) and commenting the second to last argument (preprocessing = preprocesisng) in the second to last cell (the build_model call). The same error appears.

cc @carlosuc3m

**Comment by carlosuc3m** [comment]
It seems that it is trying to iterate over the variable `attachments` while this variable is set to `None` if there is no pre- and post-processing. A workaround could be to create is as an empy list.
The lines of interest:
* Where attachments is asigned to None: https://github.com/bioimage-io/core-bioimage-io-python/blob/187e10fcecfd6aad97f889e91afca2fd34f86d31/bioimageio/core/build_spec/build_model.py#L356
* Where attachments is iterated: https://github.com/bioimage-io/core-bioimage-io-python/blob/187e10fcecfd6aad97f889e91afca2fd34f86d31/bioimageio/core/build_spec/build_model.py#L412

**Comment by carlosuc3m** [comment]
CAn you please @ivan-ea test it with @FynnBe changes.
Thanks to both of you!

**Comment by ivan-ea** [comment]
I just tested using the new version of the code. The error seems to be solved. 
Thanks a lot.
