### ISSUE TITLE
Running a model doesn't work when zenodo is down or without internet connection

### ISSUE THREAD

**Issue by jhennies** [bioimage-io/core-bioimage-io-python#376]
@FynnBe, I do remember you saying that you will move away from zenodo, but in the meantime this issue still bugs me quite a bit when running a lot of jobs on the cluster and then zenodo deciding to be down for a couple of minutes, thus killing my workfow...
As a sidenote, on the cluster the caching of the model does not seem to work, probably because I'm on a different node each time? So it downloads the model including the weights every time if I use:

```
rdf_doi = "10.5281/zenodo.7274275"
model_resource = bioimageio.core.load_resource_description(rdf_doi)
```

I tried to make myself independent of an internet connection by first downloading the model weights (i.e. the torchscript) and then loading the CebraNET model like so:

```
rdf_path = '/path/to/cebranet-cellular-membranes-in-volume-sem_torchscript.zip'
model_resource = bioimageio.core.load_resource_description(rdf_path)
```

This only works partially, the weights are not downloaded anymore, however still the readme and model.py are downloaded and if that fails I get the not availabe error:

```
RuntimeError: Failed to download https://zenodo.org/api/records/8123818/files/CebraNET_README.md/content (503 Server Error: Service Unavailable for url: https://zenodo.org/api/records/8123818/files/CebraNET_README.md/content)
```

Is there anything I can do differently to avoid the requirement for contacting zenodo entirely?

**Comment by FynnBe** [comment]
you can download (package) the model once and then use that local package to avoid connection issues.
it will be hopefully more stable soon when we have fully moved to the EBI's s3 backend, but using a local package is the best you can do for stability in general

**Comment by FynnBe** [comment]
here is how to get a local package:
```python
from pathlib import Path
from bioimageio.core import save_bioimageio_package  # or save_bioimageio_package_as_folder

url = "https://example.com/bioimageio.yaml"
local_path = save_bioimageio_package(url, output_path=Path("local_package.zip"))

description_from_local = load_description(local_path)
```

**Comment by jhennies** [comment]
Thanks @FynnBe, I'll try it out
