### ISSUE TITLE
imageio version too restrictive?

### ISSUE THREAD

**Issue by danifranco** [bioimage-io/core-bioimage-io-python#382]
Hello team,

Just noticed that in your `setup.py` you require a too high imageio package version: `"imageio>=2.5"`. Actually, correct me if I'm wrong or I missed something, but the highest `imageio` version is `2.34.1` (checked [here](https://pypi.org/project/imageio/)). For us, that we are installing your package so we can export [BiaPy](https://github.com/BiaPyX/BiaPy) models into the BMZ format, that dependency is forcing pip to install the lastest version available of `imageio`, which leds to a kernel reload in our notebooks (which is tedious for the end user). Google Colab env now has already installed `2.31.6` version so I would suggest, if it's possible and you really don't need the newest version of `imageio`, to decrease its version requirement to something above `2.31.6` (e.g. `"imageio>=2.31.6"`).  

Thank you so much!

Dani

**Comment by FynnBe** [comment]
Hi Dani, 
thank you for taking such a close look at our setup.py. 
AFAIK the imageio pin `>=2.5` does not imply that the first digit of the minor release needs to be a 5, but rather that the minor release needs to be 5 or higher. In other words `2.31` satisfies this pin as it is.
Have you tried to pin imageio to `<2.34` (if that is the version causing issues for you)?

**Comment by danifranco** [comment]
Omg, that's true. I was reading `2.50` always. I'm sorry seems that I'm too sleepy today! Closing this...
