### ISSUE TITLE
Half precision support?

### ISSUE THREAD

**Issue by benjijamorris** [bioimage-io/core-bioimage-io-python#392]
Hi there! I'm interested in contributing a model that was trained with 16bit precision, using float32 uses up >40Gb of GPU memory and would limit the utility of having the model in bioimage.io. Is there any work going on to cast model weights / inputs to 16bit precision? Apologies if I missed this in the docs and thanks for your work on this project!

**Comment by FynnBe** [comment]
Thanks @benjijamorris for your inquiry!

In principal we already support various dtypes. To use them an input (or output) tensor may specify it's `data.type` field:
a tensor's `data` field: https://bioimage-io.github.io/spec-bioimage-io/bioimageio/spec/model/v0_5.html#TensorDescrBase.data
the `type` field of the  tensor data description: https://bioimage-io.github.io/spec-bioimage-io/bioimageio/spec/model/v0_5.html#IntervalOrRatioDataDescr.type

As we may not have used this in practice ever, please do not hesitate to reopen this issue and comment here, if you encounter any issue!
