### ISSUE TITLE
`bioimageio.core.test_model` skip checking `pytorch_state_dict` if `torchscript` is given

### ISSUE THREAD

**Issue by qin-yu** [bioimage-io/core-bioimage-io-python#396]
I read the code and it seems to be a design choice. I think this behaviour should change and it should test all weight formats by default, because I was surprised. I know in the end bioimage.io only needs one working thing to run, preferably a torchscript. But in case new users are surprised in the future, I propose: 

1. If `weight_format` is `None`, then test all. 
2. If any of the formats passed the tests and others don't, the failed ones could either be removed with warning, or give errors.

**Comment by FynnBe** [comment]
thanks! yeah, that sounds like a very reasonable change! 👍

**Comment by FynnBe** [comment]
(And I'd say failed tests for specific weight formats should give errors)
