### ISSUE TITLE
Missed function in package

### ISSUE THREAD

**Issue by yhfu2307** [bioimage-io/core-bioimage-io-python#422]
I got the error information as 'cannot import name 'resolve_local_source' from 'bioimageio.core.resource_io.utils' (/usr/local/lib/python3.10/dist-packages/bioimageio/core/resource_io/utils.py)'. I wonder which version of bioimageio.core contains this function.

**Comment by FynnBe** [comment]
The last bioimage.core version with this function is 0.4.7: https://github.com/bioimage-io/core-bioimage-io-python/blob/4fdbf4c3790712032046e4f533ada4a0cd614802/bioimageio/core/resource_io/utils.py#L225
