### ISSUE TITLE
Issue with predict_many in bioimageio.core using Python 3.10.12

### ISSUE THREAD

**Issue by falibabaei** [bioimage-io/core-bioimage-io-python#423]
Hi,

I am using bioimageio.core==0.6.9 with Python 3.10.12. When I call predict_many from bioimageio.core, I encounter the following error:
 ```python
if not isinstance(inputs, collections.Mapping):
    sample_id = str(sample_id)
    if "{i}" not in sample_id and "{i:" not in sample_id:
        # Your logic here
 ```
The error occurs because collections.Mapping has been deprecated in Python 3.10+. However, the issue is resolved when I modify the code to use collections.abc.Mapping.
It looks like this change is necessary for compatibility with Python>3.10 and later versions.

**Comment by FynnBe** [comment]
thanks for reporting this issue! 👍
