### ISSUE TITLE
ChannelAxis object too rigid for channel invariant models.

### ISSUE THREAD

**Issue by ThibautGoldsborough** [bioimage-io/core-bioimage-io-python#442]
Hello, 

I'm trying to convert the [instanseg](https://github.com/instanseg/instanseg) models to your v0_5 specs. One of our models takes an arbitrary number of input channels. 

At the moment it seems ChannelAxis takes a list of channel names and if len(channel names) does not match the input tensor shape then it throws an error. 

I'm tempted to go around this by replacing ChannelAxis with SpaceInputAxis(id=AxisId("c"), but will this lead to downstream issues?

Best,

**Comment by FynnBe** [comment]
Maybe `IndexAxis` would be more suitable. 
The axis types are mostly to inform (programmatic) model users how to use the model.
With such a custom axes adding a description would be very nice (`IndexAxis(description=...)`).

**Comment by FynnBe** [comment]
for the input axis you should use [`IndexInputAxis`](https://bioimage-io.github.io/core-bioimage-io-python/bioimageio/spec/model/v0_5.html#IndexInputAxis) to be precise

**Comment by ThibautGoldsborough** [comment]
Thank you!
