### ISSUE TITLE
Implement common functionality here

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#74]
As discussed in https://github.com/bioimage-io/bioimage.io/issues/28#issuecomment-881508842 and elsewhere, it would be good to implement general purpose (python) modelzoo functionality in this repo:
- model loading (currently `tiktorch.get_nn_instance`, but extend with proper weight initialization)
- pre/post-processing + model runner (currently `tiktorch.PredictionPipeline`)
- use zenodo API to download and upload models
- refactor parts of bioimageio.spec? e.g. https://github.com/bioimage-io/spec-bioimage-io/blob/main/bioimageio/spec/build_spec.py

I think this would be a good item for the upcoming hackathon(s).

**Comment by FynnBe** [comment]
> use zenodo API to download and upload models

this could potentially live in `bioimageio.spec` as well as we have other io functionality there already.

**Comment by constantinpape** [comment]
> this could potentially live in `bioimageio.spec` as well as we have other io functionality there already.

I think we need to discuss which functionality goes to `spec` and which to `python`.

I would rather move all the non-validation functionality to `python`, but I would suggest to have the detailed discussion about this on Friday.

**Comment by FynnBe** [comment]
> I would rather move all the non-validation functionality to python, but I would suggest to have the detailed discussion about this on Friday.

yes makes sense. some of the io functionality will have to remain in spec as it is required to gather everything to do the validation...

**Comment by oeway** [comment]
> > I would rather move all the non-validation functionality to python, but I would suggest to have the detailed discussion about this on Friday.
> 
> yes makes sense. some of the io functionality will have to remain in spec as it is required to gather everything to do the validation...

Sounds like the good direction to go.
