### ISSUE TITLE
Implement download functionality

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#80]
It would be very helpful to have download functionality, i.e. a function that takes the zenodo DOI for a model and then downloads the zip; similar to the download function on bioimage.io.

@FynnBe can we refactor the packaging part of the ilastik bioimageio app for this?

**Comment by FynnBe** [comment]
yes, `bioimageio.spec.export_package`[https://github.com/bioimage-io/spec-bioimage-io/blob/b316d19510fabef9ceb72d473cf07b90fbf1960d/bioimageio/spec/__init__.py#L8]

the doi wouldn't be enough though (this we should add!), but a url to the rdf.yaml would work already.

**Comment by constantinpape** [comment]
> yes, [`bioimageio.spec.export_package`](https://github.com/bioimage-io/spec-bioimage-io/blob/b316d19510fabef9ceb72d473cf07b90fbf1960d/bioimageio/spec/__init__.py#L8)
> 

Ok, cool!

> the doi wouldn't be enough though (this we should add!), but a url to the rdf.yaml would work already.

Yes, would be good to export the doi, but for now the url to the rdf.yaml also works.

It would be good to add some more docstrings.

**Comment by FynnBe** [comment]
> It would be good to add some more docstrings.

added some more in https://github.com/bioimage-io/spec-bioimage-io/pull/197

**Comment by FynnBe** [comment]
> Yes, would be good to export the doi, but for now the url to the rdf.yaml also works.

maybe that's better implmented in a separate function as pointing to the `rdf.yaml` instead of the original content of the `doi` is a bit too much magic for comfort I think... Also this would probably be specific to zenodo (I don't see a generic way of pointing to the rdf.yaml instead of the 'landing page')...

**Comment by constantinpape** [comment]
> maybe that's better implmented in a separate function as pointing to the `rdf.yaml` instead of the original content of the `doi` is a bit too much magic for comfort I think...

I agree; I think we need a `zenodo` specific module anyway (which also deals with the upload) and this functionality could go in there and use `export_package` internally.

**Comment by constantinpape** [comment]
@FynnBe this came up in the last modelzoo call again. 
Specifically, @esgomezm got feedback from the ZIDAS course that downloading the model from the website and then entering the local path to the model in deepimageJ or ilastik was quite confusing for some users.
So we thought that it would be good to support using the DOI as model identifier everywhere and then just download in deepimagej / ilastik.
So it would be great to support passing the DOI (and I think it would even be best to support this in the high level functions like `load_resource_description` or `export_resource_package`).

**Comment by FynnBe** [comment]
one important detail (you maybe already clarified?):
Obviously dois as URLs is boring: https://doi.org/10.1109/5.771073.
So we expect "naked" dois to work? or with some hint like a "doi:" scheme
 - "naked" 10.1109/5.771073
 - "doi scheme" doi:10.1109/5.771073

**Comment by FynnBe** [comment]
assuming we want "naked" doies to work I will check if the source string matches the doi regex fully,,,

**Comment by constantinpape** [comment]
We want "naked" dois, as this is what is used as id on bioimage.io.

**Comment by FynnBe** [comment]
First step in progress: https://github.com/bioimage-io/spec-bioimage-io/pull/251 add support for doi validation in bioimageio.spec
