### ISSUE TITLE
Package scope and name

### ISSUE THREAD

**Issue by oeway** [bioimage-io/core-bioimage-io-python#85]
Hi, a quick thought here regarding the package name.

When I see it from the first time, I feel the current name `bioimageio.core` is not clear. Basically, "the core of bioimageio" can mean the core of the bioimage.io website, or something unclear. It can also make people wonder what is bioimageio first. But for us, bioimageio is just a domain name that includes the bioimage model zoo.

We should think about what the scope of the package is. As I understand, we are implementing the model inference (perhaps also training in the future), one question is that are we going to also deal with other RDFs (dataset, application, workflow) in the same package? Considering that they can be significantly different from the way we deal with models, we might want to split into smaller python modules. 

If that's the case, I would propose to reserve the name `core` and use something like `bioimageio.runner` or `bioimageio.model-runner` for the model. It will also be more clear because it means "the model runner of bioimage.io".

What do you think?

@FynnBe @constantinpape @k-dominik

**Comment by constantinpape** [comment]
We had a discussion about this and thought that core is fine because this package is only used in the python context in any case.

> use something like `bioimageio.runner` or `bioimageio.model-runner` for the model. It will also be more clear because it means "the model runner of bioimage.io".

This package contains more than model inference though, for example the `build_spec` and `weight_converter` functionality.

**Comment by FynnBe** [comment]
maybe we come up with something better... let's keep track of discussed options:
 | bioimageio.x | pro | contra |
| --- | --- | --- |
| **core** | covers various functionality we want to include there | somewhat unsepcific |
 | runner | | we also have other funtionality in there |
| model-x | | there will always be shared python funcitonality acrross resource types... ( this does not mean we might not add more specific packages in the future) |
| utils | | too vague, used also internally |
| | | |

**Comment by constantinpape** [comment]
We have decided on `core-bioimage-io-python` for the repo name and `bioimageio.core` for the package name now.
