### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/core-bioimage-io-python#98]
Here's a list of remaining issues with the functionality here I found while working on #92.
It would be good to fix some of this before making a release, maybe except for last two points, which could be a bit more complicated.

- [x] `prediction_pipeline` (and transitively also prediction functions) only support a single input/output tensor; need example model for this
- [x] `prediction_pipeline` misses output_dtype
- [x] `prediction_pipeline` does not support models with fixed output shape
- [x] the pre/postprocessing is not quite consistent with https://github.com/bioimage-io/spec-bioimage-io/blob/main/supported_formats_and_operations.md
- [x] prediction with tiling currently only works for same output shape, but supporting changes in output shape is possible (need example model)
- [ ] issues with normalization only based on local patches, e.g. for tiling, should fix by implementing and using the `per_dataset` mode

**Comment by constantinpape** [comment]
@FynnBe I think it would be good to work on this (at least first 4 points) before releasing this library. I can work on the pre/post-processing things next. And we can maybe discuss how to split the other things in the bioimage.io meeting.

**Comment by constantinpape** [comment]
Support for multiple tensors has been implemented in #103 and #104 and the output_dtype is not relevant any more since `prediction_pipeline` has `output_specs` now. 

@FynnBe do you want to tackle fixed shapes next? You can use [this model](https://github.com/bioimage-io/spec-bioimage-io/tree/main/example_specs/models/unet2d_fixed_shape) for tests.

Also, do you want to work on removing the attributes that duplicate stuff from input/output spec in prediction_pipeline? I think it would be good to also simplify that part before the release.

**Comment by FynnBe** [comment]
Yes and yes 👍

**Comment by FynnBe** [comment]
> Also, do you want to work on removing the attributes that duplicate stuff from input/output spec in prediction_pipeline? I think it would be good to also simplify that part before the release.

simplified in #106 

we could take it a step further and remove `crreate_prepdiction_pipeline` and use its `__init__` instead, as it's rather trivial now.

**Comment by FynnBe** [comment]
> @FynnBe do you want to tackle fixed shapes next? You can use this model for tests.

fixed shapes PR: https://github.com/bioimage-io/python-bioimage-io/pull/105
